export const MANUAL_INFERENCE_ORACLE = {
  status: 200,
  responseKeys: [
    "ok",
    "persisted",
    "operatorTriggeredOnly",
    "providerStatus",
    "persistence",
    "connectorStatuses",
    "participantOutputs",
    "aggregateRatification",
    "evidencePointers",
    "nonAuthorizations",
  ],
  persistenceKeys: ["id", "status", "safeAdvisoryMessage", "createdAt"],
  connectorStatusKeys: [
    "roleSlotId",
    "status",
    "nonAuthorityDisclaimer",
  ],
  historyKeys: [
    "motionId",
    "motionTitle",
    "sourceMode",
    "connectorStatusSummary",
    "participantOutputs",
    "aggregateAdvisoryRatification",
    "evidencePointers",
    "nonAuthorizations",
  ],
  historySourceModes: [
    "mock",
    "provider",
    "provider_disabled",
    "provider_unavailable",
    "persistence_staged",
  ],
  responseNonAuthorizations: [
    "JAI vote is not CONTROL_THREAD approval.",
    "JAI ratification is not final authority.",
    "Human / CONTROL_THREAD approval remains required.",
    "No autonomous execution.",
    "No GitHub mutation.",
    "No PR creation.",
    "No branch mutation.",
    "No merge action.",
    "No branch deletion.",
    "No production gate opening.",
    "No source-of-truth transfer.",
    "No hidden background execution.",
    "No automatic route execution.",
    "No work-packet execution.",
    "Provider output is advisory only.",
    "Provider connector is server-side only.",
    "Provider mode is disabled by default.",
    "Mock mode remains default.",
    "No provider API key persistence.",
    "No provider API key exposure.",
    "No provider secret storage.",
  ],
  historyNonAuthorizations: [
    "Stored deliberation is not CONTROL_THREAD approval.",
    "Stored JAI vote is not route authority.",
    "Stored ratification is not final authority.",
    "Stored provider output is not source-of-truth transfer.",
    "Stored evidence pointer is not validation approval.",
    "Stored work-packet draft is not routed work.",
    "Human / CONTROL_THREAD approval remains required.",
    "Persistence does not create execution authority.",
    "Persistence does not create GitHub mutation authority.",
    "Persistence does not create production gate authority.",
    "Persistence does not create source-of-truth authority.",
    "Persistence does not create route authority.",
    "Persistence does not create acceptance authority.",
    "No provider API key persistence.",
    "No provider API key exposure.",
    "No provider secret storage.",
  ],
} as const;
