export const MOTION_INTAKE_ORACLE = {
  statuses: {
    list: 200,
    missingDraft: 400,
    createSucceeded: 200,
  },
  keys: {
    list: ["ok", "records", "motionBases", "nonAuthorizations"],
    missingDraft: ["ok", "error", "nonAuthorizations"],
    createSucceeded: ["ok", "record", "motionBasis", "nonAuthorizations"],
  },
  missingDraftError:
    "Missing motion intake draft. No motion was persisted, routed, approved, or executed.",
  nonAuthorizations: [
    "Persisted motion is not approved work.",
    "Persisted motion is not routed work.",
    "Persisted motion is not CONTROL_THREAD acceptance.",
    "Persisted motion is not autonomous execution.",
    "Persisted target thread is not route authority.",
    "Persisted repo target is not repo execution authority.",
    "Persisted evidence pointer is not validation approval.",
    "Selected persisted motion basis is not final authority.",
    "CONTROL_THREAD remains authority.",
    "Linear remains a temporary mirror only.",
    "No autonomous execution.",
    "No GitHub mutation.",
    "No PR creation.",
    "No branch mutation.",
    "No merge action.",
    "No branch deletion.",
    "No production gate opening.",
    "No source-of-truth transfer.",
    "No auto-submit to agents.",
    "No auto-run deliberation.",
    "No auto-route work.",
    "No work-packet execution.",
    "No provider API key persistence.",
    "No provider API key exposure.",
    "No provider secret storage.",
  ],
} as const;
