export const PASSALONG_ORACLE = {
  statuses: {
    list: 200,
    invalidCreate: 400,
    writeSucceeded: 200,
    writeFailed: 400,
    detailMethodNotAllowed: 405,
  },
  availability: {
    succeeded: true,
    failed: true,
    unavailable: false,
  },
  keys: {
    list: ["ok", "records", "persistence", "nonAuthorizations"],
    invalidCreate: ["ok", "error", "errors", "nonAuthorizations"],
    write: [
      "ok",
      "record",
      "errors",
      "persistence",
      "nonAuthorizations",
    ],
    detailMethodNotAllowed: ["ok", "error", "nonAuthorizations"],
  },
  errors: {
    invalidCreate:
      "Passalong field boundary validation blocked persistence; no record was saved.",
    detailMethodNotAllowed:
      "Direct passalong mutation endpoint supports PATCH only. It does not send, route, execute, or approve passalongs.",
  },
  nonAuthorizations: [
    "Persisted passalong record is app-local and non-authoritative.",
    "Persisted passalong record is not source of truth.",
    "Persisted passalong record is not CONTROL_THREAD acceptance.",
    "Persisted route status is descriptive metadata only.",
    "Persisted route status is not route authority.",
    "Persisted lifecycle state does not alter CONTROL_THREAD decisions.",
    "Evidence pointer references are not validation approval.",
    "Manual notes are not route authority.",
    "CONTROL_THREAD remains authority.",
    "Linear remains temporary mirror only.",
    "No automatic passalong sending.",
    "No automatic route execution.",
    "No JAI Agent activation.",
    "No Agent PR Factory activation.",
    "No sandbox runtime activation.",
    "No sandbox task execution.",
    "No target-repo import.",
    "No GitHub mutation.",
    "No PR creation.",
    "No branch mutation.",
    "No merge action.",
    "No branch deletion.",
    "No deployment.",
    "No production gate opening.",
    "No source-of-truth transfer.",
  ],
} as const;
