export const PROGRAM_LIFECYCLE_MUTATION_SEAM_REGISTRY_VERSION = "c13-program-lifecycle-mutation-seam-registry/v1" as const;

export const PROGRAM_LIFECYCLE_SEAM_DISPOSITIONS = Object.freeze([
  "CANONICAL_AND_GUARDED",
  "CLASSIFICATION_ONLY",
  "DOCUMENTARY_ONLY",
  "FORMALLY_DEPRECATED_AND_UNREACHABLE",
  "UNRESOLVED_BYPASS",
] as const);

export type ProgramLifecycleSeamDisposition = (typeof PROGRAM_LIFECYCLE_SEAM_DISPOSITIONS)[number];

export type ProgramLifecycleMutationSeam = Readonly<{
  readonly id: string;
  readonly path: string;
  readonly symbol: string;
  readonly surfaceClass: "PURE" | "ROUTE" | "SERVER" | "ADAPTER" | "CLIENT" | "DISPLAY" | "SCHEMA" | "MIGRATION";
  readonly effectClass: "NONE" | "PERSISTENCE_BOUNDARY" | "RAW_SQL_PERSISTENCE" | "LIFECYCLE_TRANSACTION" | "IN_MEMORY_DRAFT" | "DECLARATIVE";
  readonly triggerClass: "DIRECT" | "REQUEST" | "ADAPTER" | "SUPPLIED_SNAPSHOT" | "DECLARATION";
  readonly guardEvidence: string;
  readonly canonicalBoundary: string;
  readonly disposition: ProgramLifecycleSeamDisposition;
  readonly replacement: string | null;
  readonly writeCapable: boolean;
  readonly evidencePosture: "STATIC_SOURCE" | "DECLARATIVE_ONLY" | "SUPPLIED_SNAPSHOT";
  readonly authorityEffect: "NONE";
  readonly mutationAuthorized: false;
}>;

const seams: readonly ProgramLifecycleMutationSeam[] = [
  { id: "C13-SEAM-001", path: "portal/src/lib/controlPlane/programLifecycle/one-active-program-invariant.ts", symbol: "evaluateOneActiveProgramInvariant", surfaceClass: "PURE", effectClass: "NONE", triggerClass: "DIRECT", guardEvidence: "C1 exact input and active-count invariant", canonicalBoundary: "C1", disposition: "CANONICAL_AND_GUARDED", replacement: null, writeCapable: false, evidencePosture: "STATIC_SOURCE", authorityEffect: "NONE", mutationAuthorized: false },
  { id: "C13-SEAM-002", path: "portal/src/lib/controlPlane/programLifecycle/canonical-active-program-resolver.ts", symbol: "resolveCanonicalActiveProgram", surfaceClass: "PURE", effectClass: "NONE", triggerClass: "DIRECT", guardEvidence: "C2 delegates to C1", canonicalBoundary: "C2", disposition: "CANONICAL_AND_GUARDED", replacement: null, writeCapable: false, evidencePosture: "STATIC_SOURCE", authorityEffect: "NONE", mutationAuthorized: false },
  { id: "C13-SEAM-003", path: "portal/src/lib/controlPlane/programLifecycle/program-state-transition-matrix.ts", symbol: "evaluateProgramStateTransition", surfaceClass: "PURE", effectClass: "NONE", triggerClass: "DIRECT", guardEvidence: "C3 exact transition matrix", canonicalBoundary: "C3", disposition: "CANONICAL_AND_GUARDED", replacement: null, writeCapable: false, evidencePosture: "STATIC_SOURCE", authorityEffect: "NONE", mutationAuthorized: false },
  { id: "C13-SEAM-004", path: "portal/src/lib/controlPlane/programLifecycle/program-activation-eligibility-gate.ts", symbol: "evaluateProgramActivationEligibility", surfaceClass: "PURE", effectClass: "NONE", triggerClass: "DIRECT", guardEvidence: "C4 classification-only eligibility", canonicalBoundary: "C4", disposition: "CANONICAL_AND_GUARDED", replacement: null, writeCapable: false, evidencePosture: "STATIC_SOURCE", authorityEffect: "NONE", mutationAuthorized: false },
  { id: "C13-SEAM-005", path: "portal/src/lib/controlPlane/programLifecycle/program-activation-authority-handler.ts", symbol: "createProgramActivationAuthorityHandler", surfaceClass: "SERVER", effectClass: "NONE", triggerClass: "REQUEST", guardEvidence: "C5 ADMIN authentication before body parsing", canonicalBoundary: "C5", disposition: "CLASSIFICATION_ONLY", replacement: null, writeCapable: false, evidencePosture: "STATIC_SOURCE", authorityEffect: "NONE", mutationAuthorized: false },
  { id: "C13-SEAM-006", path: "portal/src/app/api/operator/program-lifecycle/activation-authority/route.ts", symbol: "POST", surfaceClass: "ROUTE", effectClass: "NONE", triggerClass: "REQUEST", guardEvidence: "C5 POST delegates only to authenticated classifier", canonicalBoundary: "C5", disposition: "CLASSIFICATION_ONLY", replacement: null, writeCapable: false, evidencePosture: "STATIC_SOURCE", authorityEffect: "NONE", mutationAuthorized: false },
  { id: "C13-SEAM-007", path: "portal/src/lib/controlPlane/programLifecycle/program-lifecycle-persistence-boundary.ts", symbol: "createProgramLifecyclePersistenceService", surfaceClass: "PURE", effectClass: "PERSISTENCE_BOUNDARY", triggerClass: "ADAPTER", guardEvidence: "C6A exact adapter and invariant validation", canonicalBoundary: "C6A", disposition: "CANONICAL_AND_GUARDED", replacement: null, writeCapable: true, evidencePosture: "STATIC_SOURCE", authorityEffect: "NONE", mutationAuthorized: false },
  { id: "C13-SEAM-008", path: "portal/src/lib/controlPlane/programLifecycle/program-lifecycle-persistence.ts", symbol: "insertInitialProgramLifecycleRecord", surfaceClass: "SERVER", effectClass: "PERSISTENCE_BOUNDARY", triggerClass: "DIRECT", guardEvidence: "C6 facade delegates to C6A server adapter", canonicalBoundary: "C6", disposition: "CANONICAL_AND_GUARDED", replacement: null, writeCapable: true, evidencePosture: "STATIC_SOURCE", authorityEffect: "NONE", mutationAuthorized: false },
  { id: "C13-SEAM-009", path: "portal/src/lib/controlPlane/programLifecycle/program-lifecycle-persistence.ts", symbol: "insertInitialProgram", surfaceClass: "ADAPTER", effectClass: "RAW_SQL_PERSISTENCE", triggerClass: "ADAPTER", guardEvidence: "C6 local adapter INSERTs program_lifecycle_records", canonicalBoundary: "C6", disposition: "CANONICAL_AND_GUARDED", replacement: null, writeCapable: true, evidencePosture: "STATIC_SOURCE", authorityEffect: "NONE", mutationAuthorized: false },
  { id: "C13-SEAM-010", path: "portal/src/lib/controlPlane/programLifecycle/program-activation-supersession-boundary.ts", symbol: "createProgramActivationSupersessionService", surfaceClass: "PURE", effectClass: "LIFECYCLE_TRANSACTION", triggerClass: "ADAPTER", guardEvidence: "C7 transition, CAS, and rollback behavior plus C8 command parsing, fingerprinting, replay/conflict evaluation, receipt-draft construction, persistence invocation, and returned receipt-set coherence", canonicalBoundary: "C7/C8", disposition: "CANONICAL_AND_GUARDED", replacement: null, writeCapable: true, evidencePosture: "STATIC_SOURCE", authorityEffect: "NONE", mutationAuthorized: false },
  { id: "C13-SEAM-011", path: "portal/src/lib/controlPlane/programLifecycle/program-activation-supersession.ts", symbol: "executeProgramActivationSupersession", surfaceClass: "SERVER", effectClass: "LIFECYCLE_TRANSACTION", triggerClass: "DIRECT", guardEvidence: "C7/C8 facade delegates command parsing, replay/conflict, transactional lifecycle mutation, receipt persistence, and receipt-set validation to the guarded service", canonicalBoundary: "C7/C8", disposition: "CANONICAL_AND_GUARDED", replacement: null, writeCapable: true, evidencePosture: "STATIC_SOURCE", authorityEffect: "NONE", mutationAuthorized: false },
  { id: "C13-SEAM-012", path: "portal/src/lib/controlPlane/programLifecycle/program-activation-supersession.ts", symbol: "transaction", surfaceClass: "ADAPTER", effectClass: "LIFECYCLE_TRANSACTION", triggerClass: "ADAPTER", guardEvidence: "C7/C8 local adapter locks the portfolio, evaluates stored command/receipt replay state, performs lifecycle and command/receipt writes, and returns the coherent receipt set within prisma.$transaction", canonicalBoundary: "C7/C8", disposition: "CANONICAL_AND_GUARDED", replacement: null, writeCapable: true, evidencePosture: "STATIC_SOURCE", authorityEffect: "NONE", mutationAuthorized: false },
  { id: "C13-SEAM-013", path: "portal/src/lib/controlPlane/programLifecycle/program-activation-supersession.ts", symbol: "setProgramLifecycleState", surfaceClass: "ADAPTER", effectClass: "RAW_SQL_PERSISTENCE", triggerClass: "ADAPTER", guardEvidence: "C7 local CAS UPDATE of program_lifecycle_records", canonicalBoundary: "C7", disposition: "CANONICAL_AND_GUARDED", replacement: null, writeCapable: true, evidencePosture: "STATIC_SOURCE", authorityEffect: "NONE", mutationAuthorized: false },
  { id: "C13-SEAM-014", path: "portal/src/lib/controlPlane/programLifecycle/program-activation-supersession.ts", symbol: "insertProgramTransitionReceiptSet", surfaceClass: "ADAPTER", effectClass: "RAW_SQL_PERSISTENCE", triggerClass: "ADAPTER", guardEvidence: "C8 atomic command and receipt INSERTs inside C7 transaction", canonicalBoundary: "C8", disposition: "CANONICAL_AND_GUARDED", replacement: null, writeCapable: true, evidencePosture: "STATIC_SOURCE", authorityEffect: "NONE", mutationAuthorized: false },
  { id: "C13-SEAM-015", path: "portal/src/lib/controlPlane/programLifecycle/program-transition-receipt-boundary.ts", symbol: "createProgramTransitionReceiptSetDraft", surfaceClass: "PURE", effectClass: "IN_MEMORY_DRAFT", triggerClass: "DIRECT", guardEvidence: "C8 frozen in-memory receipt-set draft", canonicalBoundary: "C8", disposition: "CANONICAL_AND_GUARDED", replacement: null, writeCapable: false, evidencePosture: "STATIC_SOURCE", authorityEffect: "NONE", mutationAuthorized: false },
  { id: "C13-SEAM-016", path: "portal/src/lib/controlPlane/programLifecycle/program-binding-propagation-boundary.ts", symbol: "compareProgramBindingSnapshots", surfaceClass: "PURE", effectClass: "NONE", triggerClass: "SUPPLIED_SNAPSHOT", guardEvidence: "C9 supplied-snapshot comparison", canonicalBoundary: "C9", disposition: "CLASSIFICATION_ONLY", replacement: null, writeCapable: false, evidencePosture: "SUPPLIED_SNAPSHOT", authorityEffect: "NONE", mutationAuthorized: false },
  { id: "C13-SEAM-017", path: "portal/src/lib/controlPlane/programLifecycle/downstream-active-program-guard.ts", symbol: "evaluateDownstreamActiveProgramGuard", surfaceClass: "PURE", effectClass: "NONE", triggerClass: "SUPPLIED_SNAPSHOT", guardEvidence: "C10 downstream active-Program guard", canonicalBoundary: "C10", disposition: "CLASSIFICATION_ONLY", replacement: null, writeCapable: false, evidencePosture: "SUPPLIED_SNAPSHOT", authorityEffect: "NONE", mutationAuthorized: false },
  { id: "C13-SEAM-018", path: "portal/src/lib/controlPlane/programLifecycle/frozen-program-protection-boundary.ts", symbol: "evaluateFrozenProgramProtection", surfaceClass: "PURE", effectClass: "NONE", triggerClass: "SUPPLIED_SNAPSHOT", guardEvidence: "C11 frozen-Program classifier", canonicalBoundary: "C11", disposition: "CLASSIFICATION_ONLY", replacement: null, writeCapable: false, evidencePosture: "SUPPLIED_SNAPSHOT", authorityEffect: "NONE", mutationAuthorized: false },
  { id: "C13-SEAM-019", path: "portal/src/lib/controlPlane/programLifecycle/founder-active-program-control-surface.ts", symbol: "buildFounderActiveProgramControlSurface", surfaceClass: "DISPLAY", effectClass: "NONE", triggerClass: "SUPPLIED_SNAPSHOT", guardEvidence: "C12 supplied documentary model", canonicalBoundary: "C12", disposition: "DOCUMENTARY_ONLY", replacement: null, writeCapable: false, evidencePosture: "SUPPLIED_SNAPSHOT", authorityEffect: "NONE", mutationAuthorized: false },
  { id: "C13-SEAM-020", path: "portal/src/app/operator/program-lifecycle/FounderActiveProgramControlSurface.tsx", symbol: "createC5ClassificationTransport", surfaceClass: "CLIENT", effectClass: "NONE", triggerClass: "REQUEST", guardEvidence: "C12 explicit POST transport to C5 classifier", canonicalBoundary: "C12", disposition: "CLASSIFICATION_ONLY", replacement: null, writeCapable: false, evidencePosture: "SUPPLIED_SNAPSHOT", authorityEffect: "NONE", mutationAuthorized: false },
  { id: "C13-SEAM-021", path: "portal/src/app/operator/program-lifecycle/FounderActiveProgramControlSurface.tsx", symbol: "createClassificationRequestBoundary", surfaceClass: "CLIENT", effectClass: "NONE", triggerClass: "REQUEST", guardEvidence: "C12 two-step request ownership and cancellation boundary", canonicalBoundary: "C12", disposition: "CLASSIFICATION_ONLY", replacement: null, writeCapable: false, evidencePosture: "SUPPLIED_SNAPSHOT", authorityEffect: "NONE", mutationAuthorized: false },
  { id: "C13-SEAM-022", path: "portal/src/app/operator/program-lifecycle/FounderActiveProgramControlSurface.tsx", symbol: "FounderActiveProgramControlSurface", surfaceClass: "CLIENT", effectClass: "NONE", triggerClass: "REQUEST", guardEvidence: "C12 interactive client wires the C5 classification transport and request-ownership boundary", canonicalBoundary: "C12", disposition: "CLASSIFICATION_ONLY", replacement: null, writeCapable: false, evidencePosture: "SUPPLIED_SNAPSHOT", authorityEffect: "NONE", mutationAuthorized: false },
  { id: "C13-SEAM-023", path: "portal/src/app/operator/program-lifecycle/page.tsx", symbol: "ProgramLifecyclePage", surfaceClass: "DISPLAY", effectClass: "NONE", triggerClass: "SUPPLIED_SNAPSHOT", guardEvidence: "C12 supplied documentary page", canonicalBoundary: "C12", disposition: "DOCUMENTARY_ONLY", replacement: null, writeCapable: false, evidencePosture: "SUPPLIED_SNAPSHOT", authorityEffect: "NONE", mutationAuthorized: false },
  { id: "C13-SEAM-024", path: "portal/prisma/schema.prisma", symbol: "model ProgramLifecycleRecord", surfaceClass: "SCHEMA", effectClass: "DECLARATIVE", triggerClass: "DECLARATION", guardEvidence: "C6/C7 lifecycle record declaration", canonicalBoundary: "C6/C7", disposition: "DOCUMENTARY_ONLY", replacement: null, writeCapable: false, evidencePosture: "DECLARATIVE_ONLY", authorityEffect: "NONE", mutationAuthorized: false },
  { id: "C13-SEAM-025", path: "portal/prisma/schema.prisma", symbol: "model ProgramTransitionCommand", surfaceClass: "SCHEMA", effectClass: "DECLARATIVE", triggerClass: "DECLARATION", guardEvidence: "C8 transition-command declaration", canonicalBoundary: "C8", disposition: "DOCUMENTARY_ONLY", replacement: null, writeCapable: false, evidencePosture: "DECLARATIVE_ONLY", authorityEffect: "NONE", mutationAuthorized: false },
  { id: "C13-SEAM-026", path: "portal/prisma/schema.prisma", symbol: "model ProgramLifecycleTransitionReceipt", surfaceClass: "SCHEMA", effectClass: "DECLARATIVE", triggerClass: "DECLARATION", guardEvidence: "C8 transition-receipt declaration", canonicalBoundary: "C8", disposition: "DOCUMENTARY_ONLY", replacement: null, writeCapable: false, evidencePosture: "DECLARATIVE_ONLY", authorityEffect: "NONE", mutationAuthorized: false },
  { id: "C13-SEAM-027", path: "portal/prisma/migrations/20260730040000_add_program_lifecycle_persistence/migration.sql", symbol: "CREATE TABLE \"program_lifecycle_records\"", surfaceClass: "MIGRATION", effectClass: "DECLARATIVE", triggerClass: "DECLARATION", guardEvidence: "C6 declarative lifecycle table migration", canonicalBoundary: "C6", disposition: "DOCUMENTARY_ONLY", replacement: null, writeCapable: false, evidencePosture: "DECLARATIVE_ONLY", authorityEffect: "NONE", mutationAuthorized: false },
  { id: "C13-SEAM-028", path: "portal/prisma/migrations/20260730070000_add_program_lifecycle_version/migration.sql", symbol: "ALTER TABLE \"program_lifecycle_records\"", surfaceClass: "MIGRATION", effectClass: "DECLARATIVE", triggerClass: "DECLARATION", guardEvidence: "C7 declarative lifecycle-version migration", canonicalBoundary: "C7", disposition: "DOCUMENTARY_ONLY", replacement: null, writeCapable: false, evidencePosture: "DECLARATIVE_ONLY", authorityEffect: "NONE", mutationAuthorized: false },
  { id: "C13-SEAM-029", path: "portal/prisma/migrations/20260730190000_add_program_transition_receipt_idempotency/migration.sql", symbol: "CREATE TABLE \"program_transition_commands\"", surfaceClass: "MIGRATION", effectClass: "DECLARATIVE", triggerClass: "DECLARATION", guardEvidence: "C8 declarative transition-command migration", canonicalBoundary: "C8", disposition: "DOCUMENTARY_ONLY", replacement: null, writeCapable: false, evidencePosture: "DECLARATIVE_ONLY", authorityEffect: "NONE", mutationAuthorized: false },
  { id: "C13-SEAM-030", path: "portal/prisma/migrations/20260730190000_add_program_transition_receipt_idempotency/migration.sql", symbol: "CREATE TABLE \"program_lifecycle_transition_receipts\"", surfaceClass: "MIGRATION", effectClass: "DECLARATIVE", triggerClass: "DECLARATION", guardEvidence: "C8 declarative transition-receipt migration", canonicalBoundary: "C8", disposition: "DOCUMENTARY_ONLY", replacement: null, writeCapable: false, evidencePosture: "DECLARATIVE_ONLY", authorityEffect: "NONE", mutationAuthorized: false },
  { id: "C13-SEAM-031", path: "portal/src/lib/controlPlane/programLifecycle/program-lifecycle-reconciliation-recovery-boundary.ts", symbol: "reconcileProgramLifecycleFaultAndRehearseRollback", surfaceClass: "PURE", effectClass: "NONE", triggerClass: "SUPPLIED_SNAPSHOT", guardEvidence: "C14 supplied-snapshot fault reconciliation, human-review reporting, and in-memory rollback rehearsal only", canonicalBoundary: "C14", disposition: "CLASSIFICATION_ONLY", replacement: null, writeCapable: false, evidencePosture: "SUPPLIED_SNAPSHOT", authorityEffect: "NONE", mutationAuthorized: false },
];

export const PROGRAM_LIFECYCLE_MUTATION_SEAM_REGISTRY = Object.freeze(seams.map((seam) => Object.freeze({ ...seam })));
