import type { RouteDecisionNonAuthorizations } from "./routeDecisionTypes";

export const SHARED_FALLBACK_ROUTE_DECISION_NON_AUTHORIZATIONS = [
  "CONTROL_THREAD remains authority.",
  "Human / CONTROL_THREAD approval remains required.",
  "No autonomous execution.",
  "No route authority is granted.",
  "No execution authority is granted.",
  "No acceptance authority is transferred.",
  "No automatic route execution.",
  "No automatic delivery.",
  "Provider output remains advisory only.",
  "No provider API key persistence.",
  "No provider API key exposure.",
  "No provider secret storage.",
] as const satisfies RouteDecisionNonAuthorizations;

export const PASSALONG_PERSISTENCE_NON_AUTHORIZATIONS = [
  "Persisted passalong record is app-local and non-authoritative.",
  "Persisted passalong record is not source of truth.",
  "Persisted passalong record is not CONTROL_THREAD acceptance.",
  "Persisted route status is descriptive metadata only.",
  "Persisted route status is not route authority.",
  "Persisted lifecycle state does not alter CONTROL_THREAD decisions.",
  "Evidence pointer references are not validation approval.",
  "Manual notes are not route authority.",
  "CONTROL_THREAD remains authority.",
  "Linear remains temporary mirror only.",
  "No automatic passalong sending.",
  "No automatic route execution.",
  "No JAI Agent activation.",
  "No Agent PR Factory activation.",
  "No sandbox runtime activation.",
  "No sandbox task execution.",
  "No target-repo import.",
  "No GitHub mutation.",
  "No PR creation.",
  "No branch mutation.",
  "No merge action.",
  "No branch deletion.",
  "No deployment.",
  "No production gate opening.",
  "No source-of-truth transfer.",
] as const satisfies RouteDecisionNonAuthorizations;

export const MOTION_INTAKE_ROUTE_NON_AUTHORIZATIONS = [
  "Persisted motion is not approved work.",
  "Persisted motion is not routed work.",
  "Persisted motion is not CONTROL_THREAD acceptance.",
  "Persisted motion is not autonomous execution.",
  "Persisted target thread is not route authority.",
  "Persisted repo target is not repo execution authority.",
  "Persisted evidence pointer is not validation approval.",
  "Selected persisted motion basis is not final authority.",
  "CONTROL_THREAD remains authority.",
  "Linear remains a temporary mirror only.",
  "No autonomous execution.",
  "No GitHub mutation.",
  "No PR creation.",
  "No branch mutation.",
  "No merge action.",
  "No branch deletion.",
  "No production gate opening.",
  "No source-of-truth transfer.",
  "No auto-submit to agents.",
  "No auto-run deliberation.",
  "No auto-route work.",
  "No work-packet execution.",
  "No provider API key persistence.",
  "No provider API key exposure.",
  "No provider secret storage.",
] as const satisfies RouteDecisionNonAuthorizations;

export const MANUAL_INFERENCE_RESPONSE_NON_AUTHORIZATIONS = [
  "JAI vote is not CONTROL_THREAD approval.",
  "JAI ratification is not final authority.",
  "Human / CONTROL_THREAD approval remains required.",
  "No autonomous execution.",
  "No GitHub mutation.",
  "No PR creation.",
  "No branch mutation.",
  "No merge action.",
  "No branch deletion.",
  "No production gate opening.",
  "No source-of-truth transfer.",
  "No hidden background execution.",
  "No automatic route execution.",
  "No work-packet execution.",
  "Provider output is advisory only.",
  "Provider connector is server-side only.",
  "Provider mode is disabled by default.",
  "Mock mode remains default.",
  "No provider API key persistence.",
  "No provider API key exposure.",
  "No provider secret storage.",
] as const satisfies RouteDecisionNonAuthorizations;

export const MANUAL_INFERENCE_HISTORY_NON_AUTHORIZATIONS = [
  "Stored deliberation is not CONTROL_THREAD approval.",
  "Stored JAI vote is not route authority.",
  "Stored ratification is not final authority.",
  "Stored provider output is not source-of-truth transfer.",
  "Stored evidence pointer is not validation approval.",
  "Stored work-packet draft is not routed work.",
  "Human / CONTROL_THREAD approval remains required.",
  "Persistence does not create execution authority.",
  "Persistence does not create GitHub mutation authority.",
  "Persistence does not create production gate authority.",
  "Persistence does not create source-of-truth authority.",
  "Persistence does not create route authority.",
  "Persistence does not create acceptance authority.",
  "No provider API key persistence.",
  "No provider API key exposure.",
  "No provider secret storage.",
] as const satisfies RouteDecisionNonAuthorizations;

export function routeDecisionNonAuthorizations(
  value: RouteDecisionNonAuthorizations,
): string[] {
  return [...value];
}
