name: Deploy dev.jai.nexus

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/configure-pages@v5
      - uses: actions/upload-pages-artifact@v3
        with:
          path: .
  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: github-pages
      # quoting avoids YAML “flow-map-start” false positives in linters
      url: "${{ steps.deployment.outputs.page_url }}"
    steps:
      - id: deployment
        uses: actions/deploy-pages@v4