name: Deploy dev.jai.nexus
on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: pages
  cancel-in-progress: true

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Prepare static site
        run: |
          mkdir -p .site
          rsync -a --delete \
            --exclude '.git*' \
            --exclude '.github' \
            --exclude '.venv' \
            --exclude '.cache' \
            --exclude 'scripts' \
            --exclude 'Makefile*' \
            --exclude 'README.md' \
            ./ .site/
          # Ensure these two markers make it into the artifact
          [ -f CNAME ] && cp CNAME .site/ || true
          [ -f .nojekyll ] && cp .nojekyll .site/ || true

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: .site

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
